// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeiErpFuDp-mnUTOA_qwmP8wJf1RcWYIQ',
    appId: '1:1097568563666:web:207a0719d49fffd295980b',
    messagingSenderId: '1097568563666',
    projectId: 'petperks-c209c',
    authDomain: 'petperks-c209c.firebaseapp.com',
    storageBucket: 'petperks-c209c.firebasestorage.app',
    measurementId: 'G-LM6GHEFWRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA35fXiVqn4I3TXnh3hQuQZotUlMAZ8jQs',
    appId: '1:1097568563666:android:4c5819bfeeaa188595980b',
    messagingSenderId: '1097568563666',
    projectId: 'petperks-c209c',
    storageBucket: 'petperks-c209c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKAovlQugtHfpJOQMAoK1kVabPmk8BwWc',
    appId: '1:1097568563666:ios:058aa66605709a7395980b',
    messagingSenderId: '1097568563666',
    projectId: 'petperks-c209c',
    storageBucket: 'petperks-c209c.firebasestorage.app',
    iosBundleId: 'com.example.petperks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKAovlQugtHfpJOQMAoK1kVabPmk8BwWc',
    appId: '1:1097568563666:ios:058aa66605709a7395980b',
    messagingSenderId: '1097568563666',
    projectId: 'petperks-c209c',
    storageBucket: 'petperks-c209c.firebasestorage.app',
    iosBundleId: 'com.example.petperks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeiErpFuDp-mnUTOA_qwmP8wJf1RcWYIQ',
    appId: '1:1097568563666:web:8f205db39cd4ac7395980b',
    messagingSenderId: '1097568563666',
    projectId: 'petperks-c209c',
    authDomain: 'petperks-c209c.firebaseapp.com',
    storageBucket: 'petperks-c209c.firebasestorage.app',
    measurementId: 'G-B1PCE62X4H',
  );
}
